### ISSUE TITLE
Crash on Android 4.4.2

### ISSUE THREAD

**Issue by linrium** [noke-inc/noke-mobile-library-android#2]
I received an error from Fabric (on Android 4.4.2 Wiko Rainbow 4G). I also created React native module for Noke: [https://github.com/Ant-Tech-Agency/react-native-noke](https://github.com/Ant-Tech-Agency/react-native-noke). Do you have any ideas? Thanks

Fatal Exception: java.lang.NullPointerException
       at android.os.Parcel.readException(Parcel.java:1471)
       at android.os.Parcel.readException(Parcel.java:1419)
       at android.bluetooth.IBluetoothGatt$Stub$Proxy.stopScan(IBluetoothGatt.java:724)
       at android.bluetooth.BluetoothAdapter$GattCallbackWrapper.stopLeScan(BluetoothAdapter.java:1611)
       at android.bluetooth.BluetoothAdapter.stopLeScan(BluetoothAdapter.java:1555)
       at com.noke.nokemobilelibrary.NokeDeviceManagerService.stopLeScanning(NokeDeviceManagerService.java:489)
       at com.noke.nokemobilelibrary.NokeDeviceManagerService.turnOffBLEScan(NokeDeviceManagerService.java:431)
       at com.noke.nokemobilelibrary.NokeDeviceManagerService.access$000(NokeDeviceManagerService.java:70)
       at com.noke.nokemobilelibrary.NokeDeviceManagerService$1.run(NokeDeviceManagerService.java:389)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5315)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by sapsley** [comment]
It appears this error is related to the bluetooth stack on the phone itself. Does this crash happen consistently on the device? Have you tried restarting the device and running the app again?  A restart on Android devices flushes out the bluetooth cache and often resolves weird bugs like this.

**Comment by linrium** [comment]
@sapsley thank you
